
name: General Issue
description: Report a UI, Page, CSS, Bug, Backend, or any other issue
title: "[Issue]: "
labels: ["triage"]

body:
  - type: dropdown
    attributes:
      label: Issue Type
      description: Select the type of issue
      options:
        - UI Change
        - Page Update
        - CSS Improvement
        - Bug
        - Backend / API
        - Performance
        - Security
        - Other (please specify below)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Issue Description
      description: Describe the issue in detail
      placeholder: What is the problem or requested change?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Outcome
      description: What should happen after this issue is resolved?
      placeholder: Describe the expected behavior or result
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Details (for Other / Bug / Backend)
      description: Logs, screenshots, steps, or any extra info
      placeholder: Error logs, steps to reproduce, API response, etc.
    validations:
      required: false

